
services:

  provider:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: provider
    network_mode: host
    cap_add:
      - NET_ADMIN

networks:
  backend:
    driver: bridge
